fofa/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('swot.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # Quando for pro lordi
# urlpatterns = [
#     path('fofa/', include('swot.urls')),
#     path('fofa/users/', include('django.contrib.auth.urls')),
#     path('fofa/users/', include('users.urls')),
#     path('fofa/admin/', admin.site.urls),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swot/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('adicionar_planejamento', adicionar_planejamento, name='adicionar_planejamento'),
    
    path('fatores/<int:id>', fatores, name='fatores'),
    path('objetivo/<int:id>', objetivo, name='objetivo'),
    path('elementos/<int:id>', elementos, name='elementos'),
    path('adicionar_fatores/<int:id>', adicionar_fatores, name='adicionar_fatores'),
    path('adicionar_objetivo/<int:id>', adicionar_objetivo, name='adicionar_objetivo'),
    path('liderElemento/<int:id>/<int:membro>', liderElemento, name='liderElemento'),
    path('comentarioFator/<int:id>', comentarioFator, name='comentarioFator'),
    path('comentarioObjetivo/<int:id>', comentarioObjetivo, name='comentarioObjetivo'),

    path('editarMembro/<int:id_plan>/<int:id_memb>', editarMembro, name='editarMembro'),
    path('editarFator/<int:id>', editarFator, name= 'editarFator'),


    path('base',base,name='base'),
    path('teste',teste,name='teste'),
]

swot/models.py
from django.db import models
from datetime import date
# Create your models here.


class Planejamento(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.CharField(max_length=150, blank=True, null=True)
    lider = models.ForeignKey('users.Membro', on_delete=models.CASCADE, related_name='plan_lider_rel')
    membros = models.ManyToManyField('users.Membro', blank=True, null=True, related_name='plan_membros_rel')
    prazo = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.titulo
    
    @property
    def prazo_final(self):
        return date.today() < self.prazo


class Elementos(models.Model):
    planejamento = models.ForeignKey('Planejamento', on_delete=models.CASCADE, blank=True, null=True)
    tipo_elemento = models.CharField(max_length=20)
    descricao = models.TextField(blank=True, null=True)
    lider = models.ForeignKey('users.Membro', on_delete=models.CASCADE, blank=True, null=True)
    member = models.ManyToManyField('users.Membro', blank=True, null=True, related_name='elementos_membros_rel')

    def __str__(self):
        return self.tipo_elemento


class Fatores(models.Model):
    planejamento = models.ForeignKey('Planejamento', on_delete=models.CASCADE, blank=True, null=True)
    elemento = models.ForeignKey('Elementos', on_delete=models.CASCADE)
    descricao = models.TextField()
    criador = models.ForeignKey('users.Membro', on_delete=models.CASCADE, blank=True, null=True)
    
    def __str__(self):
        return self.descricao


class Objetivo(models.Model):
    elemento = models.ForeignKey('Elementos', on_delete=models.CASCADE, blank=True, null=True)
    fator=models.ForeignKey('Fatores', on_delete=models.CASCADE, null=True)
    descricao = models.TextField()
    concluido = models.BooleanField(default=False)
    criador = models.ForeignKey('users.Membro', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.descricao)


class ComentarioFator(models.Model):
    fator = models.ForeignKey('Fatores', on_delete=models.CASCADE)
    membro = models.ForeignKey('users.Membro', on_delete=models.CASCADE)
    comentario = models.TextField()
    horario = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.comentario


class ComentarioObjetivo(models.Model):
    objetivo = models.ForeignKey('Objetivo', on_delete=models.CASCADE)
    membro = models.ForeignKey('users.Membro', on_delete=models.CASCADE)
    comentario = models.TextField()
    horario = models.DateTimeField(auto_now=True, blank=True, null=True)
    
    def __str__(self):
        return self.comentario

swot/forms.py
from django import forms
from .models import *


class FatoresForm(forms.ModelForm):
    class Meta:
        model= Fatores
        fields= ('descricao',)


class PlanejamentoForm(forms.ModelForm):
    class Meta:
        model = Planejamento
        fields = ('titulo','descricao')


class ObjetivoForm(forms.ModelForm):
    class Meta:
        model= Objetivo
        fields= ('descricao',)


class ObjetivoConcluidoForm(forms.ModelForm):
    class Meta:
        model= Objetivo
        fields= ('descricao','concluido')


class ComentarioFatorForm(forms.ModelForm):
    class Meta:
        model= ComentarioFator
        fields= ('comentario',)

swot/views.py
from fofa.settings import ALLOWED_HOSTS
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from datetime import date, datetime

from .models import *
from users.models import *
from .forms import *

app_name= 'swot'

lista_fofa = ['Forças','Oportunidades','Fraquezas','Ameaças']
desc_fofa = [
    'Representa as qualidades positivas da empresa, ou seja, tudo aquilo que agrega valores e está sob o controle da organização.',
    'São fatores externos (que não estão sob a influência da empresa) e quando surgem, trazem benefícios para a corporação. EX: uma nova lei que possa beneficiar a empresa de algum modo.',
    'São pontos que atrapalham e não trazem vantagens competitivas para a corporação. Assim como as Forças, as Fraquezas também estão sob o comando da empresa.',
    'Também não estão sob o controle da empresa, porém são fatores que podem prejudicar a corporação de algum modo. Um exemplo pode ser a entrada de uma grande empresa no segmento.'
]
# Create your views here.


def base(request):
    a=12
    return render(request, 'base.html',{'a':a})


@login_required
def home(request):
    membro = Membro.objects.get(usuario=request.user)
    conv = Convite.objects.filter(convidado = membro)
    plan = Planejamento.objects.filter(membros = membro)
    return render(request, 'swot/home.html', {'plan':plan, 'membro':membro, 'conv':conv})


@login_required
def elementos(request, id):
    plan = Planejamento.objects.get(id=id)
    elementos= Elementos.objects.filter(planejamento=plan)
    fatores = Fatores.objects.filter(planejamento = plan)
    return render(request, 'swot/elementos.html', {'elementos':elementos, 'plan':plan, 'fatores':fatores})


def fatores(request, id):
    elemento=Elementos.objects.get(id=id)
    fatores=Fatores.objects.filter(elemento=elemento)
    objetivos = Objetivo.objects.filter(elemento=elemento)
    return render(request, 'swot/fatores.html',{'elemento':elemento,'fatores':fatores, 'objetivos':objetivos})


def objetivo(request, id):
    objetivo=Objetivo.objects.get(id=id)
    form = ObjetivoConcluidoForm(request.POST or None, instance=objetivo)
    coment = ComentarioObjetivo.objects.filter(objetivo=objetivo)
    if form.is_valid():
        form.save()
        return redirect('swot:fatores', objetivo.fator.elemento.id)
    else:
        return render(request, 'swot/objetivo.html',{'objetivo':objetivo, 'form':form, 'coment':coment})


def editarMembro(request, id_plan, id_memb):
    plan = Planejamento.objects.get(id=id_plan)
    elementos = Elementos.objects.filter(planejamento = plan)
    membro = Membro.objects.get(id = id_memb)
    
    if request.method == "POST":
        forca = request.POST.get('força', 'Nao encontrado')
        oport = request.POST.get('oport', 'Nao encontrado')
        fraq = request.POST.get('fraq', 'Nao encontrado')
        ameac = request.POST.get('ameac', 'Nao encontrado')

        fo = elementos[0]
        op = elementos[1]
        fr = elementos[2]
        am = elementos[3]
    
        if forca == 'on':
            fo.member.add(membro)
            fo.save()
        else:
            fo.member.remove(membro)
            fo.save()

        if oport == 'on':
            op.member.add(membro)
            op.save()
        else:
            op.member.remove(membro)
            op.save()

        if fraq == 'on':
            fr.member.add(membro)
            fr.save()
        else:
            fr.member.remove(membro)
            fr.save()

        if ameac == 'on':
            am.member.add(membro)
            am.save()
        else:
            am.member.remove(membro)
            am.save()

    return render(request, 'swot/editarMembro.html', {'plan':plan, 'membro':membro, 'elementos':elementos})


def adicionar_fatores(request, id):
    membro = Membro.objects.get(usuario = request.user)
    elemento=Elementos.objects.get(id=id)
    form=FatoresForm(request.POST or None)
    if form.is_valid():
        add_fat=form.save(commit=False)
        add_fat.planejamento = elemento.planejamento
        add_fat.criador = membro
        add_fat.elemento = elemento
        add_fat.save()
        return redirect('swot:fatores', id)
    else:
        return render(request,'swot/adicionar_fatores.html', {'form':form, 'elemento':elemento})


def editarFator(request, id):
    fator = Fatores.objects.get(id=id)
    form = FatoresForm(request.POST or None, instance=fator)
    coment = ComentarioFator.objects.filter(fator=fator)
    if form.is_valid():
        form.save()
        return redirect('swot:fatores', fator.elemento.id)
    else:
        return render(request, 'swot/editarFator.html', {'fator':fator, 'form':form, 'coment':coment})


def adicionar_objetivo(request, id):
    membro = Membro.objects.get(usuario = request.user)
    fator=Fatores.objects.get(id=id)
    form = ObjetivoForm(request.POST or None)
    if form.is_valid():
        add_obj = form.save(commit=False)
        add_obj.criador = membro
        add_obj.fator = fator
        add_obj.elemento = fator.elemento
        add_obj.concluido = False
        add_obj.save()
        return redirect('swot:fatores', fator.elemento.id)
    else:
        return render(request,'swot/adicionar_objetivo.html', {'form':form, 'fator':fator})


# def adicionar_planejamento(request):
#     membro=Membro.objects.get(usuario=request.user)
#     form=PlanejamentoForm(request.POST or None)
#     if form.is_valid():
#         plan=form.save(commit=False)
#         plan.lider = membro
#         plan.save()
#         plan.membros.add(membro)
#         plan.save()
#         for i in range(4):
#             element= Elementos()
#             element.planejamento=plan
#             element.tipo_elemento = lista_fofa[i]
#             element.descricao = desc_fofa[i]
#             element.save()
#         conv = Convite()
#         conv.planejamento = plan
#         conv.lider = membro
#         conv.save()
#         return redirect('swot:home')
#     else:
#         return render(request,'swot/adicionar_planejamento.html', {'form':form})

def adicionar_planejamento(request):
    membro=Membro.objects.get(usuario=request.user)
    if request.method == "POST":
        plan=Planejamento()
        plan.titulo = request.POST['titulo']
        plan.descricao = request.POST['descricao']
        plan.prazo = request.POST['prazo']
        plan.lider = membro
        plan.save()
        plan.membros.add(membro)
        plan.save()
        for i in range(4):
            element= Elementos()
            element.planejamento=plan
            element.tipo_elemento = lista_fofa[i]
            element.descricao = desc_fofa[i]
            element.save()
        conv = Convite()
        conv.planejamento = plan
        conv.lider = membro
        conv.save()
        return redirect('swot:home')
    else:
        return render(request,'swot/adicionar_planejamento.html')


def liderElemento(request, membro, id):
    elemento = Elementos.objects.get(id=id)
    membro = Membro.objects.get(id=membro)

    if elemento.lider != None:
        print('tem gente')
        elemento.lider = membro
        elemento.save()
    else:
        print('tem gente n')
        elemento.lider = membro
        elemento.save()

    return redirect ('swot:elementos', elemento.planejamento.id)


def comentarioFator(request, id):
    membro = Membro.objects.get(usuario = request.user)
    fator = Fatores.objects.get(id=id)
    form = ComentarioFator()
    if request.method == "POST":
        form.comentario = request.POST['message']
        form.fator = fator
        form.membro = membro
        form.save()
    return redirect('swot:editarFator', id)


def comentarioObjetivo(request, id):
    membro = Membro.objects.get(usuario = request.user)
    objetivo = Objetivo.objects.get(id=id)
    form = ComentarioObjetivo()
    if request.method == "POST":
        form.comentario = request.POST['message']
        form.objetivo = objetivo
        form.membro = membro
        form.save()
    return redirect('swot:objetivo', id)


def teste(request):
    return render(request, 'swot/teste.html')

swot/templates/swot/editarFator.html
{% extends 'base.html' %}

{% block title %} Editar Fator {%endblock%}

{% block content %}

<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">
      <ol>
        <li><a href="{% url 'swot:home' %}">Home</a></li>
        <li><a href="{% url 'swot:elementos' fator.elemento.planejamento.id %}">Elementos</a></li>
        <li><a href="{% url 'swot:fatores' fator.elemento.id %}">Fatores</a></li>
        <li>Fator</li>
      </ol>
    </div>
  </section><!-- End Breadcrumbs -->

<!-- ======= Contact Section ======= -->
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>{{fator}}</h2>
    </div>

    <div class="row">
      <div class="d-flex align-items-stretch">
        {% if request.user == fator.criador.usuario or request.user == fator.planejamento.lider.usuario or request.user == fator.elemento.lider.usuario %}
        <form method="POST" class="php-email-form">
            {% csrf_token %}
            <div class="form-group col-md-12">
              <label for="descricao">Descricao</label>
              <textarea class="form-control" name="descricao" id="descricao" cols="30" rows="10" required>{{fator}}</textarea>
              <!-- <input type="text" name="descricao" class="form-control" id="descricao"> -->
            </div>
          <div class="atualizar">
            <button type="submit">Atualizar</button>
          </div>
        </form>
        {%endif%}
      </div>

      <!-- <div class="col-lg-4 mt-5 mt-lg-0 d-flex align-items-stretch">
        <img class="novo-planejamento" src="static/assets/img/novo_planejamento.jpg" alt="">
      </div> -->

    </div> <!--fim do row-->

  </div>
</section><!-- End Contact Section -->

<!-- ======= Comentarios Section ======= -->
<section id="comentarios" class="comentarios">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>Comentários ({{coment.count}})</h2>
    </div>

    <div class="row">
      <div class="col-lg-0 mt-5 mt-lg-0 d-flex align-items-stretch">
        <form  method="post" action="{% url 'swot:comentarioFator' fator.id %}" role="form" class="php-email-form">
          {%csrf_token%}
          <div class="row">
          <div class="form-group">
            <label for="name">Faça um comentário:</label>
            <textarea class="form-control" name="message" rows="3" required></textarea>
          </div>
          <div class="my-3">
            <div class="loading">Loading</div>
            <div class="error-message"></div>
            <div class="sent-message">Your message has been sent. Thank you!</div>
          </div>
          <div class="text-center"><button type="submit">Comentar</button></div>
        </form>
      </div>

    </div><!--Fim do row-->

  </div>
</section><!-- End Comentários Section -->


<section id="todos-coments" class="todos-coments section-bg">
  <div class="container" data-aos="fade-up">

    <div class="row">

      <div class="col-lg-10">
        {% for comentario in coment %}
          <div class="member d-flex align-items-start">
            <div class="pic">
              {% if comentario.membro.avatar %}
                <img src="/media/{{comentario.membro.avatar}}" class="img-fluid" alt="">
              {% else %}
                <img src="/static/assets/img/team/user.png" class="img-fluid" alt="">
              {% endif %}
            </div>
            <div class="member-info">
              <h4>{{comentario.membro.nome}}</h4>
              <span>{{comentario.horario}}</span>
              <p>{{comentario.comentario}}</p>
              <div class="social">
                <a href="#">like</a>
                <a href="#">deslike</a>
              </div>
            </div>
          </div>
          {% empty %}
            Sem comentários.
          {%endfor%}
      </div>

    </div>

  </div>
</section><!-- End Team Section -->


{% endblock %}

swot/templates/swot/fatores.html
{% extends 'base.html' %}

{% block title %} Fatores {%endblock%}

{% block content %} 

<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
  <div class="container">
    <ol>
      <li><a href="{% url 'swot:home' %}">Home</a></li>
      <li><a href="{% url 'swot:elementos' elemento.planejamento.id %}">Elementos</a></li>
      <li>Fatores</li>
    </ol>
  </div>
</section><!-- End Breadcrumbs -->


<!-- ======= Frequently Asked Questions Section ======= -->
<section id="fatores" class="fatores section-bg">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>Fatores: {{elemento}}</h2>
      <p>Aqui você visualiza e define quais fatores são os(as) <strong>{{elemento}}</strong> da sua organização <strong>{{elemento.planejamento}}</strong>. Cada fator é composto por uma série de <strong>ações</strong> para mantê-lo. Portanto, sua equipe deve decidir quais <strong>ações</strong> deverão ser tomadas. :D</p>
    </div>

    <div class="fatores-list">
      <div data-aos="fade-up" data-aos-delay="100">
        <br><a href="{% url 'swot:adicionar_fatores' elemento.id %}">Novo Fator <i class="bx bx-plus-circle"></i></a>
      </div><br>
      <ul>
        {% for i in fatores %}
          <!-- Se quiser tudo aberto: primeira classe que encontrar substitui por class="collapsed", e a segunda que encontrar substitui por class="collapsed-show" -->
          <li data-aos="fade-up" data-aos-delay="200">
            <!-- Condição pra saber se o usuario logado foi quem criou o fator. -->
            {% if request.user == i.criador.usuario or request.user == i.planejamento.lider.usuario or request.user == i.elemento.lider.usuario %}
                <i class="bx bx-check-circle icon-help"></i> <!-- icone do "V" -->
                <a data-bs-toggle="collapse" class="collapsed" data-bs-target="#fatores-list-{{i.id}}" id="{{i.id}}">
                  #{{i.id}} {{i.descricao}} - Por {{i.criador.nome}}  <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i>
                </a>
                <a href="{% url 'swot:editarFator' i.id %}">Ver Detalhes</a>
                <!-- <a class="coment-link" href="{% url 'swot:editarFator' i.id %}">Comentários(24)</a> -->
              {% else %}
                <i class="bx bx-check-circle icon-help"></i> <!-- icone do "V" -->
                <a data-bs-toggle="collapse" class="collapsed" data-bs-target="#fatores-list-{{i.id}}">
                  {{i.descricao}} - Por {{i.criador.nome}} <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i>
                </a>
                <a href="{% url 'swot:editarFator' i.id %}">Ver Detalhes</a>
              {% endif %}

            <div id="fatores-list-{{i.id}}" class="collapse" data-bs-parent=".fatores-list">
              <p>
                {% for j in objetivos %}
                  {% if j.fator == i %}

                      <a class="letra-perfil2" href="{% url 'swot:objetivo' j.id %}">
                        <font color=#4F4F4F><i class="text-info bx bx-merge "></i> {{j}}</font>
                        <a class="letra-perfil" href="#"> - Por {{j.criador.nome}}</a>
                      </a><br>
                                        
                  {%endif%}
                {%endfor%}
                <div class="row">
                  <div class="col-md-4"></div>
                  <div class="col-md-4">
                    <div class="row">
                      <div class="col-md-2"></div>
                      <div class="col-md-8">
                        <a class= "getstarted scrollto" href="{% url 'swot:adicionar_objetivo' i.id %}">Nova Ação <i class="bx bx-plus-circle"></i></a>
                      </div>
                    </div>
                  </div>
                </div>
                  
              </p>
            </div>
          </li>
        {%endfor%}
      </ul>

    </div>
  </div>
</section><!-- End Frequently Asked Questions Section -->



{% endblock %}

swot/templates/swot/home.html
{% extends 'base.html' %}

{% block title %} Home {%endblock%}

{% block content %}

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">

  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
        <h1>Seja bem-vindo(a) ao FOFA, {{membro.nome}}.</h1>
        <h2>Melhores soluções para o seu negócio.</h2>
        <div class="d-flex justify-content-center justify-content-lg-start">
          <a href="#plan" class="btn-get-started scrollto">Vamos lá!</a>
          <!-- <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a> -->
        </div>
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
        <img src="static/assets/img/swot66.png" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>

</section><!-- End Hero -->

<!-- ======= Cliens Section ======= -->
<section id="cliens" class="cliens section-bg">
  <div class="container">

    <div class="row" data-aos="zoom-in">

      <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
        <img src="" class="img-fluid" alt="">
      </div>

      <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
        <img src="" class="img-fluid" alt="">
      </div>

      <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
        <img src="static/assets/img/clients/petcc.png" class="img-fluid" alt="">
      </div>

      <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
        <img src="static/assets/img/clients/di.png" class="img-fluid" alt="">
      </div>
      
      <!-- <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
        <img src="static/assets/img/clients/client-1.png" class="img-fluid" alt="">
      </div>

      <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
        <img src="static/assets/img/clients/client-2.png" class="img-fluid" alt="">
      </div>

      <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
        <img src="static/assets/img/clients/client-3.png" class="img-fluid" alt="">
      </div>

      <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
        <img src="static/assets/img/clients/client-4.png" class="img-fluid" alt="">
      </div>

      <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
        <img src="static/assets/img/clients/client-5.png" class="img-fluid" alt="">
      </div>

      <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
        <img src="static/assets/img/clients/client-6.png" class="img-fluid" alt="">
      </div> -->

    </div>

  </div>
</section><!-- End Cliens Section -->


<!-- ======= Why Us Section (Planejamentos) ======= -->
<section id="plan" class="why-us section-bg">
  <div class="container-fluid" data-aos="fade-up">

    <div class="row">

      <div class="col-lg-7 d-flex flex-column justify-content-center align-items-stretch  order-2 order-lg-1">

        <div class="content">
          <h3>Meus <strong>Planejamentos</strong></h3>
          <p>
            Aqui você pode ver todos os planejamentos nos quais participa.
            <br> Se for o <strong>Criador</strong> do planejamento, verá a opção <strong>Gerenciar</strong>.
            <br> Se for apenas membro, aparecerá a opção <strong>Acessar</strong>.
          </p><br>
          <p>
            <a href="{% url 'swot:adicionar_planejamento' %}">Novo Planejamento <i class="bx bx-plus-circle"></i></a>
          </p>
        </div>

      
        
        <div class="accordion-list">
          <ul>
            {% for planejamento in plan %}
              {% if planejamento.prazo_final %}
                <li>
                  <a data-bs-toggle="collapse" class="collapse" data-bs-target="#accordion-list-{{planejamento.id}}"><span>#</span> {{planejamento}} <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                  <div id="accordion-list-{{planejamento.id}}" class="collapse show" data-bs-parent=".accordion-list">
                    <p>
                      {{planejamento.descricao}} <br><br>
                      <div class="row">
                        <div class="col-md-3">
                          {% if request.user == planejamento.lider.usuario %}
                          <a href="{% url 'swot:elementos' planejamento.id %}">Gerenciar
                            <i class="bx bx-cog">  </i> <!-- não são espaços-->
                          </a>
                          {%else%}
                          <a href="{% url 'swot:elementos' planejamento.id %}">Acessar
                            <i class="bx bx-log-in-circle">   </i> <!-- não são espaços-->
                          </a>
                          {%endif%}
                        </div>
                      </div>
                    </p>
                </li>
              {% else %}
                <li>
                  <a data-bs-toggle="collapse" class="collapse" data-bs-target="#accordion-list-{{planejamento.id}}"><span>#</span> {{planejamento}} <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                  <div id="accordion-list-{{planejamento.id}}" class="collapse show" data-bs-parent=".accordion-list">
                    <p>
                      {{planejamento.descricao}} <br><br>
                      <div class="row">
                        {% if request.user == planejamento.lider.usuario %}
                          <div class="col-md-3">
                            <a href="{% url 'swot:elementos' planejamento.id %}">Gerenciar
                              <i class="bx bx-cog">  </i> <!-- não são espaços-->
                            </a>
                          </div>
                        {%else%}
                          <strong>Este planejamento encerrou-se em {{planejamento.prazo}}</strong> 
                        {%endif%}
                      </div>
                    </p>
                </li>
              {% endif %}
            {% empty %}
                <li>
                  Você ainda não possui planejamentos ativos. Para criar um, basta clicar em <strong>Novo Planejamento</strong>.
                  
                </li>
              
              {%endfor%}

          </ul>
        </div>
      </div>

      <div class="col-lg-5 align-items-stretch order-1 order-lg-2 img" style='background-image: url("static/assets/img/why-us.png");' data-aos="zoom-in" data-aos-delay="150">&nbsp;</div>
    
    </div>

  </div>
</section><!-- End Why Us Section -->




{% endblock %}