fofa/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('swot.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# # Quando for pro lordi
# urlpatterns = [
#     path('fofa/', include('swot.urls')),
#     path('fofa/users/', include('django.contrib.auth.urls')),
#     path('fofa/users/', include('users.urls')),
#     path('fofa/admin/', admin.site.urls),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('registro', registro, name='registro'),
    path('registro2', registro2, name='registro2'),
    path('login', auth_views.LoginView.as_view(template_name='registration/login.html')),
    path('adicionar_membros/<int:id>', adicionar_membros, name='adicionar_membros'),
    path('add_membro',add_membro,name='add_membro'),
    # path('add_membro/<int:id>/<int:usuario>',add_membro,name='add_membro'),
    path('getUsuarios/<int:id>', getUsuarios, name='getUsuarios'),
    path('perfil/<int:id>', perfil, name='perfil'),

    path('logar', logar_usuario, name='logar_usuario'),
    path('logout', logout_view, name='logout_view'),

    path('getConvites/<int:id>', getConvites, name='getConvites'),
    path('convites/<int:id>', convites, name='convites'),
    path('novoConvite', novoConvite, name='novoConvite'),
    # path('novoConvite/<int:convidadoId>/<int:planejamento>', novoConvite, name='novoConvite'),
    path('convRecusado/<int:id>/<int:membro>', convRecusado, name='convRecusado'),
    path('convAceito/<int:id>/<int:idplan>/<int:conv>', convAceito, name='convAceito'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.fields.related import ForeignKey, OneToOneField

# Create your models here.

class User(AbstractUser):

    def __str__(self):
        return self.username


class Membro(models.Model):
    usuario = models.ForeignKey('User', on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)

    avatar= models.ImageField(upload_to='perfil_pics',blank=True, null=True)
    facebook = models.CharField(max_length=100, blank=True, null=True, unique=True, verbose_name="Link do Facebook")
    instagram = models.CharField(max_length=100, blank=True, null=True, unique=True, verbose_name="Link do Instagram")
    linkedin = models.CharField(max_length=100, blank=True, null=True, unique=True, verbose_name="Link do Linkedin")
    twitter = models.CharField(max_length=100, blank=True, null=True, unique=True, verbose_name="Link do Twitter")
    git = models.CharField(max_length=100, blank=True, null=True, unique=True, verbose_name="Link do Git")

    def __str__(self):
        return str(self.usuario)


class Convite(models.Model):
    lider = models.ForeignKey('Membro', on_delete=models.CASCADE, related_name='lider')
    convidado = models.ManyToManyField('Membro', related_name='convidado', blank=True)
    planejamento = models.ForeignKey('swot.Planejamento', on_delete=models.CASCADE)
    # resolvido = models.BooleanField(default=False)

    def __str__(self):
        return str(self.lider)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *


class RegistroForm(UserCreationForm):
    class Meta:
        model= User
        fields= ('username','first_name', 'password1','password2')
    
    def __init__(self, *args, **kwargs):
        super(RegistroForm, self).__init__(*args, **kwargs)
        
        self.fields['password1'].widget.attrs['placeholder'] = 'Senha'
        self.fields['password2'].widget.attrs['placeholder'] = 'Repita a senha'


class PerfilForm(forms.ModelForm):
    class Meta:
        model = Membro
        fields=('nome', 'id')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.http import JsonResponse
from django.core import serializers
import json

from swot.models import *
from .models import *
from .forms import *

app_name = 'users'
# Create your views here.


def adicionar_membros(request, id):
    conv = Convite.objects.filter(planejamento = id)
    plan=Planejamento.objects.get(id=id)
    pesquisa = request.GET.get('pesquisa', None)

    if pesquisa:
        usuarios = User.objects.filter(first_name__icontains=pesquisa) # ao colocar '__icontains=' no final, serve para ignorar se a letra é maiuscula ou minuscula
    else:
        usuarios = User.objects.all()   

    return render(request,'users/adicionar_membros.html', {'plan':plan, 'usuarios':usuarios, 'conv': conv})


def getUsuarios(request, id):
    dataM = serializers.serialize("json", Membro.objects.all(), fields=('usuario', 'nome','avatar','id'))
    dataP = serializers.serialize("json", Planejamento.objects.filter(id=id), fields=('membros'))
    dataC = serializers.serialize("json", Convite.objects.filter(planejamento=id), fields=('convidado'))
    
    j = json.loads(dataM)
    p = json.loads(dataP)
    c = json.loads(dataC)

    return JsonResponse({'membros':j, 'plan':p, 'conv':c})

    # data2 = {'membros':[]}
    # for i in j:
    #     data2['membros'].append(i)
    # print (data2)
    # return JsonResponse({'membros':list(membros.values('usuario','primeiro_nome','planejamento', 'elemento','id'))})


def add_membro(request):
    if request.method == 'POST':
        membro = Membro.objects.get(usuario=request.POST['usuario'])
        plan = Planejamento.objects.get(id=request.POST['planej'])

        plan.membros.add(membro)
        plan.save()
        return redirect('users:adicionar_membros', plan.id)



# def add_membro(request):
#     if request.method == 'POST':
#         membro = Membro.objects.get(usuario=usuario)
#         plan = Planejamento.objects.get(id=id)
        
#         membro.planejamento.add(plan)
#         membro.save()

#         plan.membros.add(usuario)
#         plan.save()
#         return redirect('users:adicionar_membros', id)


def rm_membro(request, id, usuario):
    pass


def registro(request):
    form= RegistroForm(request.POST or None)
    if form.is_valid():
        usuario = form.save(commit=False)
        usuario.save()
        membro = Membro()
        membro.usuario = usuario
        membro.primeiro_nome = usuario.first_name
        membro.save()
        return redirect('swot:home')
    else:
        return render(request, 'users/registro.html', {'form':form})


def registro2(request):
    form= RegistroForm(request.POST or None)
    if request.method == "POST":
        usuario = form.save(commit=False)
        usuario.username = request.POST['username']
        usuario.first_name = request.POST['first_name']
        usuario.save()
        membro = Membro()
        membro.usuario = usuario
        membro.nome = usuario.first_name
        membro.save()
        return redirect('swot:home')
    else:
        return render(request, 'users/logar.html')


def logar_usuario(request):
    form= RegistroForm(request.POST or None)
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        usuario = authenticate(request, username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('swot:home')
        else:
            form_login = AuthenticationForm()
    else:
        form_login = AuthenticationForm()
    return render(request, 'users/logar.html', {'form_login': form_login, 'form':form})


def logout_view(request):
    logout(request)
    return redirect('/users/logar')


# CONVITES ===================================

def getConvites(request, id):
    convit = serializers.serialize("json", Convite.objects.filter(convidado=id), fields=('lider', 'convidado','planejamento','id'))
    convites = json.loads(convit)
    return JsonResponse({'convites': convites})


def convites(request, id):
    membro = Membro.objects.get(usuario=id)
    conv = Convite.objects.filter(convidado = membro)
    return render(request, 'users/convites.html', {'membro':membro, 'conv':conv})


def novoConvite(request):
    convidado = Membro.objects.get(id=request.POST['convidadoId'])
    conv = Convite.objects.get(id=request.POST['conviteId'])

    conv.convidado.add(convidado)
    conv.save()

    return redirect ('users:adicionar_membros', conv.planejamento.id)


def convAceito(request, id, idplan, conv):
    plan = Planejamento.objects.get(id=idplan)
    membro = Membro.objects.get(id=id)
    convite = Convite.objects.get(id=conv)

    convite.convidado.remove(membro)
    plan.membros.add(membro)
    plan.save()
    convite.save()

    print(convite, convite.id)

    return redirect('swot:home')


def convRecusado(request, id, membro):
    convite = Convite.objects.get(id=id)
    membr = Membro.objects.get(id=membro)
    convite.convidado.remove(membr)
    convite.save()

    return redirect('users:convites', membr.usuario.id)


# FIM DOS CONVITES ===================================


def perfil(request, id):
    membro = Membro.objects.get(usuario = id)
    form= PerfilForm(request.POST or None, instance=membro)
    if form.is_valid():
        perfil = form.save(commit=False)
        perfil.save()
        return redirect('swot:home')
    else:
        return render (request, 'users/perfil.html', {'membro':membro, 'form':form})

users/templates/users/adicionar_membros.html
{% extends 'base.html' %}

{% block title %} Adicionar Membros {%endblock%}

{% block content %}

<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

      <div class="row">
        <div class="col-8">
          <ol>
            <li><a href="{% url 'swot:home' %}">Home</a></li>
            <li><a href="{% url 'swot:elementos' plan.id %}">Elementos</a></li>
            <li>Adicionar Membros</li>
          </ol>
          <h2>Adicionar Membros ao Projeto {{plan}}</h2>
        </div>

        <div class="col">
          <div class="row"> </div>
          
          <nav class="navbar ">  <!-- Barra de Pesquisa -->
            <div class="container-fluid">
              <div class="d-flex">
                <input id="txtPesquisa" name="txtPesquisa" class="form-control me-2" type="search" placeholder="Pesquisar" aria-label="Search">
              </div>
            </div>
          </nav> <!-- Fim da barra -->

        </div>
      </div>

    </div>
</section><!-- End Breadcrumbs -->



<!-- ======= Adicionar Membros Section (team2) ======= -->

<section id="team2" class="team2">
  
  <div class="container" data-aos="fade-up">
    <div id="member_info_id" class="row">
      <!-- Ajax fazendo essa parte aqui -->
    </div>
  </div>

</section><!-- End Adicionar Membros Section -->





<script>

function get_member(){
    $.ajax({
        type: 'GET',
        url: "{% url 'users:getUsuarios' plan.id %}",
        success: function(response){
            $("#member_info_id").empty();

            for (var key in response.membros){
              if ( response.plan[0].fields.membros.includes(response.membros[key].pk) ){
                var botao = `Este usuário já participa do seu planejamento.`
                
              }
              else {
                if ( response.conv[0].fields.convidado.includes(response.membros[key].pk) ){
                  var botao = "convite foi enviado."
                }
                else {
                  var botao = ` <form id="form-post-` + response.membros[key].id + `" method="POST">
                                  {% csrf_token %}
                                  <input type="button" onclick="newConvite(` + response.membros[key].pk + `, ` + response.conv[0].pk + `)" class="btn btn-outline-info btn-sm" value="Convidar">
                                </form>`
                }
              }

              if(response.membros[key].fields.avatar != ""){
                var avatar = `<img src="/media/`+response.membros[key].fields.avatar+`" class="img-fluid" alt="">`
              }
              else{
                var avatar = `<img src="/static/assets/img/team/user.png" class="img-fluid" alt="">`
              }

              var temp = `
                <div class="col-lg-2"></div>
                <div class="col-8">
                  <div class="member">
                    <div class="d-flex align-items-start">
                      <div class="pic">
                        `+avatar+`
                      </div>
                      <div class="member-info">
                        <h4>` + response.membros[key].fields.nome + ` - ID ` + response.membros[key].pk + `</h4>
                        <p> Alguma descrição aqui, se quiser.</p>
                        <p></p>
                        ` + botao + `
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-2"></div>
                `
                
                $("#member_info_id").append(temp);
            }
        }
    })
}


function busca(value,targetSelector){
        $(targetSelector).show();
        $(targetSelector+':not(:contains("'+ value +'"))').hide();
    }
    $('#txtPesquisa').keyup(function () {
       busca($(this).val(), '.member');
    })

    
$(document).ready(function(){

    get_member(), busca()

});


function add_member(usuario, planejamento){
  $.ajax({
        type: 'POST',
        url: "{% url 'users:add_membro' %}",
        data: {
            usuario: usuario,
            planej: planejamento,
            csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
        },

        success: function(data){
            get_member()
        },
    });
}

function newConvite(convidadoId, conviteId){
  $.ajax({
        type: 'POST',
        url: "{% url 'users:novoConvite' %}",
        data: {
          convidadoId: convidadoId,
          conviteId: conviteId,
          csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
        },

        success: function(data){
            get_member()
        },
    });
}
    
  </script>


{%endblock%}

users/templates/users/convites.html
{% extends 'base.html' %}

{% block title %} Adicionar Fator {%endblock%}

{% block content %}

<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

      <ol>
        <li><a href="{% url 'swot:home' %}">Home</a></li>
        <li>Convites</li>
      </ol>
      <h2>Convites para Planejamentos</h2>

    </div>
  </section><!-- End Breadcrumbs -->

<div class="row">
    <div class="col-2"></div>
    <div class="col">
      {% for convite in conv %} <br>
        <div class="card" style="width: 50rem;">
          <div class="card-body">
            <!-- <h5 class="card-title">Card title</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
            <p class="card-text">Você recebeu uma solitação de <strong>{{convite.lider.nome}}</strong> para participar do projeto <strong>{{convite.planejamento}}.</strong></p>
            <a href="{% url 'users:convAceito' membro.id convite.planejamento.id convite.id %}" class="card-link">Aceitar</a>
            <a href="{% url 'users:convRecusado' convite.id membro.id %}" class="recusar card-link">Recusar</a>
          </div>
        </div>
      {% empty %}
      <br>
      <p>Você não possui solicitações.</p> <br><br><br><br><br><br>
      {% endfor%}
    </div>
</div>



{%endblock%}

users/templates/users/logar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FOFA Login</title>

    <link rel="stylesheet" href="/static/assets/css/logar.css">
</head>
<body>

    <!-- <h2>FOFA</h2> -->
    <div class="container" id="container">
        <div class="form-container sign-up-container">
            <form method="POST" action="{% url 'users:registro2' %}">
                {% csrf_token %}

                <h1>Criar Conta</h1>
                <span>algum texto aqui se quiser</span>
                <input type="text" id="first_name" name="first_name" placeholder="Nome" />
                <input type="text" name="username" placeholder="Usuario" />
                <!-- <input type="password" name="password1" placeholder="Senha" /> -->
                <!-- <input type="password" name="password2" placeholder="Repetir Senha" /> -->
                {{form.password1}}
                {{form.password2}}
                
                <button>Criar conta</button>
            </form>
        </div>
        <div class="form-container sign-in-container">
            <form method="POST">
                {% csrf_token %}
                <h1>Entrar</h1>
                <span>Coloque suas credenciais</span>
                <input type="text" name="username" placeholder="Usuario" />
                <input type="password" name="password" placeholder="Senha" />
                <button>Entrar</button>
                <!-- <a href="#">Esqueceu sua senha?</a> -->
            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Cadastro simples!</h1>
                    <p>Caso já possua uma conta, faça login.</p>
                    <button class="ghost" id="signIn">Fazer login</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>Seja muito bem-vindo ao FOFA!</h1>
                    <p>Caso ainda não possua uma conta em nosso sistema, você pode se registrar abaixo.</p>
                    <button class="ghost" id="signUp">Registre-se</button>
                </div>
            </div>
        </div>
    </div>



</body>

<script src="/static/assets/js/logar.js"></script>
</html>

users/templates/users/logar2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}

    <div class="form-group">
        {{form_login.username.errors}}
        <label>Username: </label>
        {{form_login.username}}
    </div>

    <div class="form-group">
        {{form_login.password.errors}}
        <label>Senha: </label>
        {{form_login.password}}
    </div>

    <div class="form-group">
        <input type="submit" value="Enviar" class="btn btn-primary">
    </div>
</form>
</body>
</html>

users/templates/users/login.html
{% extends "base.html" %}

{%block title%} Login {%endblock%}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

users/templates/users/perfil.html
{% extends 'base.html' %}

{% block title %} Perfil {%endblock%}

{% block content %}

<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

      <ol>
        <li><a href="{% url 'swot:home' %}">Home</a></li>
        <li>Convites</li>
      </ol>
      <h2>Convites para Planejamentos</h2>

    </div>
  </section><!-- End Breadcrumbs -->

<div class="row">
    <div class="col-2"></div>
    <div class="col">
        <form method="POST">
            {%csrf_token%}
            {{form.as_p}}
            {{form.errors}}
            <input type="submit" value="salvar">
        </form>
    </div>
</div>



{%endblock%}

users/templates/users/registro.html
{% extends 'base.html' %}

{% block title %} Registro {%endblock%}

{% block content %} <br><br><br><br>

<div class="col"><br>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        {{form.errors}}
        <input type="submit" class="button" value="Cadastrar">
    </form>
</div>


{% endblock %}